name: CI/CD - Flask Docker

on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE_NAME: talkeret/ci-cd-flask-app

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Build Docker container for testing
        run: docker build -t flask-test:ci .

      - name: Run container for tests
        run: |
          docker run -d --name flask-app -p 5000:5000 flask-test:ci
          sleep 5

      - name: Run pytest + health check
        run: |
          pytest
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Health check failed! HTTP code: $RESPONSE"
            exit 1
          fi

      - name: Stop test container
        run: docker rm -f flask-app || true

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build & Push Docker image
        run: |
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Deploy container
        run: |
          docker rm -f flask-app || true
          docker run -d --name flask-app -p 5000:5000 $IMAGE_NAME:$VERSION